# Using devatherock/graalvm for JDK 17
FROM devatherock/graalvm:21-ol8 AS builder

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY . /build

# Build
RUN chmod +x mvnw && \
    ./mvnw --no-transfer-progress native:compile -Pnative && \
    rm -rf /root/.m2
    
# Use a lightweight Linux base image with just enough runtime dependencies
FROM container-registry.oracle.com/os/oraclelinux:8-slim

# Set the timezone
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Copy the native executable into the containers
COPY --from=builder /build/target/gpt-4-copilot gpt-4-copilot

ENTRYPOINT ["/gpt-4-copilot"]
