# 基于Java 17的GraalVM构建镜像
FROM container-registry.oracle.com/graalvm/native-image:21-ol8 AS builder
WORKDIR /app
COPY . /app

# 安装native-image工具
RUN gu install native-image

# 使用Maven构建应用程序
RUN mvn package -DskipTests

# 使用native-image编译成本地二进制文件
RUN native-image -cp target/benchmark-jibber-0.0.1-SNAPSHOT.jar
